apiVersion: apps/v1
kind: Deployment
metadata:
  name: bespin-react-frontend2
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: frontend-fargate
  template:
    metadata:
      labels:
        app: frontend-fargate
